import { StyleSheet } from "react-native";

export const getStyles = (isDark: boolean) => {
  const colors = isDark
    ? {
        bg: "#000000",
        panel: "rgba(255, 255, 255, 0.07)",
        panelSoft: "rgba(255, 255, 255, 0.04)",
        text: "#f3f4f6",
        subtext: "#9ca3af",
        accent: "#60a5fa",
        accentStrong: "#3b82f6",
        border: "rgba(255, 255, 255, 0.14)",
        positive: "#86efac",
        negative: "#fda4af",
      }
    : {
        bg: "#000000",
        panel: "rgba(255, 255, 255, 0.07)",
        panelSoft: "rgba(255, 255, 255, 0.04)",
        text: "#f3f4f6",
        subtext: "#9ca3af",
        accent: "#60a5fa",
        accentStrong: "#3b82f6",
        border: "rgba(255, 255, 255, 0.14)",
        positive: "#86efac",
        negative: "#fda4af",
      };

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    mainContent: {
      flex: 1,
    },
    tabContainer: {
      marginHorizontal: 20,
      marginTop: 10,
      marginBottom: 14,
      backgroundColor: colors.panelSoft,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: "row",
      padding: 4,
    },
    tabButton: {
      flex: 1,
      borderRadius: 10,
      minHeight: 44,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 10,
    },
    tabButtonActive: {
      backgroundColor: "rgba(255, 255, 255, 0.12)",
    },
    tabButtonText: {
      color: colors.subtext,
      fontWeight: "600",
      fontSize: 14,
    },
    tabButtonTextActive: {
      color: colors.text,
    },
    searchContent: {
      paddingHorizontal: 20,
      paddingTop: 10,
      paddingBottom: 26,
      gap: 14,
    },
    cameraCard: {
      backgroundColor: colors.panel,
      borderRadius: 20,
      borderColor: colors.border,
      borderWidth: 1,
      padding: 14,
      shadowColor: "#000",
      shadowOpacity: 0.22,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 6 },
      elevation: 4,
    },
    cameraFrame: {
      borderRadius: 16,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: colors.border,
      height: 132,
      backgroundColor: "#000",
    },
    camera: {
      width: "100%",
      height: "100%",
    },
    scanGuideWrap: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: "center",
      alignItems: "center",
    },
    scanGuideLine: {
      width: "78%",
      height: 2,
      backgroundColor: `${colors.accent}cc`,
      borderRadius: 999,
    },
    scanEdgeMark: {
      position: "absolute",
      width: 3,
      height: "54%",
      backgroundColor: `${colors.accent}cc`,
      borderRadius: 999,
    },
    scanEdgeMarkLeft: {
      left: "11%",
    },
    scanEdgeMarkRight: {
      right: "11%",
    },
    scanHintText: {
      color: colors.subtext,
      marginTop: 12,
      fontSize: 13,
      textAlign: "center",
    },
    primaryButton: {
      marginTop: 14,
      backgroundColor: colors.accent,
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    primaryButtonText: {
      color: "#ffffff",
      fontWeight: "700",
      fontSize: 15,
    },
    secondaryButton: {
      marginTop: 12,
      backgroundColor: colors.panelSoft,
      borderRadius: 12,
      borderColor: colors.border,
      borderWidth: 1,
      paddingVertical: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    secondaryButtonText: {
      color: colors.text,
      fontWeight: "700",
      fontSize: 14,
    },
    manualCard: {
      backgroundColor: colors.panel,
      borderRadius: 20,
      borderColor: colors.border,
      borderWidth: 1,
      padding: 14,
    },
    manualTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "700",
      marginBottom: 10,
    },
    manualRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    manualInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      color: colors.text,
      backgroundColor: "rgba(255, 255, 255, 0.03)",
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 14,
    },
    manualButton: {
      backgroundColor: colors.accentStrong,
      borderRadius: 12,
      paddingVertical: 11,
      paddingHorizontal: 14,
      alignItems: "center",
      justifyContent: "center",
    },
    manualButtonText: {
      color: "#ffffff",
      fontWeight: "700",
      fontSize: 13,
    },
    analyticsContent: {
      paddingHorizontal: 20,
      paddingTop: 10,
      paddingBottom: 26,
      gap: 14,
    },
    statsGrid: {
      gap: 10,
    },
    statCard: {
      backgroundColor: colors.panel,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      padding: 14,
    },
    positiveCard: {
      borderColor: `${colors.positive}88`,
    },
    negativeCard: {
      borderColor: `${colors.negative}88`,
    },
    statLabel: {
      color: colors.subtext,
      fontSize: 13,
      fontWeight: "600",
    },
    statValue: {
      color: colors.text,
      marginTop: 6,
      fontSize: 28,
      fontWeight: "800",
      letterSpacing: 0.4,
    },
    latestCard: {
      backgroundColor: colors.panel,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      padding: 14,
    },
    latestTitle: {
      color: colors.subtext,
      fontSize: 13,
      marginBottom: 6,
    },
    latestCountry: {
      color: colors.text,
      fontSize: 23,
      fontWeight: "800",
      marginBottom: 8,
    },
    latestMeta: {
      color: colors.subtext,
      fontSize: 13,
      marginTop: 3,
    },
    latestTone: {
      marginTop: 10,
      fontWeight: "800",
      fontSize: 14,
    },
    positiveTone: {
      color: colors.positive,
    },
    negativeTone: {
      color: colors.negative,
    },
    historySection: {
      backgroundColor: colors.panel,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      padding: 14,
    },
    historyHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    historyTitle: {
      color: colors.text,
      fontWeight: "700",
      fontSize: 15,
    },
    clearHistoryText: {
      color: colors.accent,
      fontWeight: "700",
      fontSize: 13,
    },
    emptyStateCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.panelSoft,
      paddingVertical: 20,
      paddingHorizontal: 12,
    },
    emptyStateText: {
      color: colors.subtext,
      textAlign: "center",
      fontSize: 13,
    },
    historyItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      backgroundColor: colors.panelSoft,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginTop: 8,
    },
    historyCountry: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "700",
    },
    historyCode: {
      color: colors.subtext,
      fontSize: 12,
      marginTop: 2,
      maxWidth: 180,
    },
    historyRight: {
      alignItems: "flex-end",
    },
    historyTone: {
      fontSize: 12,
      fontWeight: "800",
    },
    historyTime: {
      marginTop: 3,
      color: colors.subtext,
      fontSize: 11,
    },
    centeredState: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 24,
    },
    stateTitle: {
      color: colors.text,
      fontWeight: "800",
      fontSize: 20,
      textAlign: "center",
    },
    stateText: {
      color: colors.subtext,
      marginTop: 8,
      fontSize: 14,
      textAlign: "center",
      lineHeight: 20,
    },
  });
};

export default getStyles;
