const { withAppBuildGradle } = require("@expo/config-plugins");

// Wires up a `release` signing config that reads from a gitignored
// keystore.properties file at the PROJECT ROOT (not inside android/, which
// is regenerated by `expo prebuild`/`expo run:android` and would otherwise
// wipe out any manual build.gradle edits). If keystore.properties or the
// keystore file it points to don't exist, this silently falls back to the
// debug signing config so local `expo run:android` keeps working without
// requiring every contributor to have the production keystore.
//
// keystore.properties format (see keystore.properties.example):
//   storeFile=../../release.jks   (relative to android/app/)
//   storePassword=...
//   keyAlias=...
//   keyPassword=...
module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    const marker = "// @generated withReleaseSigning";
    if (config.modResults.contents.includes(marker)) {
      return config;
    }

    // Declared at the top level of the script (not inside any closure) so
    // it's visible from both the signingConfigs {} and buildTypes {} blocks
    // further down — Groovy closures only see outer-script-scope defs, not
    // defs made inside a sibling closure.
    const preamble = `
${marker}
def keystorePropertiesFile = rootProject.file("../keystore.properties")
def keystoreProperties = new Properties()
def hasReleaseKeystore = false
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
    hasReleaseKeystore = file(keystoreProperties['storeFile']).exists()
}

`;

    let contents = config.modResults.contents.replace(
      /^android\s*\{/m,
      `${preamble}android {`
    );

    contents = contents.replace(
      /signingConfigs\s*\{/,
      `signingConfigs {
        if (hasReleaseKeystore) {
            release {
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }`
    );

    contents = contents.replace(
      /release\s*\{\s*\n\s*\/\/ Caution![^\n]*\n\s*\/\/ see[^\n]*\n\s*signingConfig signingConfigs\.debug/,
      (match) =>
        match.replace(
          "signingConfig signingConfigs.debug",
          "signingConfig hasReleaseKeystore ? signingConfigs.release : signingConfigs.debug"
        )
    );

    config.modResults.contents = contents;
    return config;
  });
};
